### ISSUE TITLE
Fix the CI deploy

### ISSUE THREAD

**Issue by chee** [Financial-Times/origami-webhooks#29]
Deploy fails because `Could not locate deployment bucket. Error: The request signature we calculated does not match the signature you provided. Check your key and signing method.` which i do not understand and cannot fix.

https://app.circleci.com/jobs/github/Financial-Times/origami-webhooks/355

**Comment by JakeChampion** [comment]
https://github.com/Financial-Times/origami-webhooks/issues/30
