### ISSUE TITLE
Decomission

### ISSUE THREAD

**Issue by chee** [Financial-Times/origami-webhooks#30]
When we disable Origami Friend, that will be the last thing using this repo so we should archive it instead of keeping up with the dependabots.

We no longer read it because it's been outflanked by [the project board](https://github.com/orgs/Financial-Times/projects/83?fullscreen=true) and Github's Slack Integration :panda_face:.

Goodbye, Origami Friend, you've served us well :vulcan_salute: 
![origami friend](https://user-images.githubusercontent.com/178266/75339386-54386500-5888-11ea-902b-413f16c2e5c7.png)

**Comment by notlee** [comment]
👍 it also posts in the uxd channel if a repo has the uxd label attached which is nice but we don't use too often

**Comment by notlee** [comment]
Decommissioning origami-webhooks:

1. mark as deprecated in bizops [done]
2. delete the test cloudformation from `aws-composer-account-origami-test`
3. delete the stack including IAM user in AWS test account 
4. all good? do step 2 and 3 for prod
5. mark as decommissioned in bizops
6. revoke non-shared keys, and delete records from lastpass/vault

Anything I missed or got wrong @Financial-Times/origami-core?

**Comment by chee** [comment]
looks right to me:)

(8. archive this repo)

**Comment by notlee** [comment]
> looks right to me:)
> 
> (8. archive this repo)

Oh!

8. Release with an updated origami.json support status
9. archive this repo

**Comment by notlee** [comment]
but actually I'll update the support status to `dead` in `origami.json` first, so I don't need to delete circle config to prevent a failed deploy
